### ISSUE TITLE
Uploading and exporting a gpx with xml escaped characters produces invalid xml/gpx

### ISSUE THREAD

**Issue by Agnox** [vcoppe/gpx-tool#2]
When you upload a GPX with xml escaped characters: IE &amp, &lt; ... and export this GPX again i will produce an invald xml/gpx file. The escape xml characters no longer are xml escaped. &ampl is converted into & and &lt; into < in the output. See attached files

[gpxstudio-xml_escaping__exported.txt](https://github.com/vcoppe/gpx-tool/files/5490041/gpxstudio-xml_escaping__exported.txt)
[gpxstudio-xml_escaping.txt](https://github.com/vcoppe/gpx-tool/files/5490043/gpxstudio-xml_escaping.txt)

**Comment by vcoppe** [comment]
Thanks for the example files, I have added the conversion in commit 0aa2eedc2066ca21409421694430539180b08a3a.
