### ISSUE TITLE
Add support for driving/motorcycling activity

### ISSUE THREAD

**Issue by tweemeterjop** [vcoppe/gpx-tool#3]
Hi! Great tool, great website! Can we add support for driving/motorcycling activity? I would love to generate tracks using this program.

**Comment by vcoppe** [comment]
Thanks! I am currently thinking of changing the routing API from Mapbox to Graphhopper.
Besides being less expensive for high volumes, it has more activity types (https://docs.graphhopper.com/#operation/getRoute/vehicle).
If I switch, I will add some of them to the interface as well.

**Comment by vcoppe** [comment]
I have added an activity type which uses the driving mode of the Mapbox Directions API.

**Comment by tweemeterjop** [comment]
Awesome! I just tested it on the live website and it works great. Thanks for adding this feature.
