### ISSUE TITLE
[question] Information about elevation data

### ISSUE THREAD

**Issue by giovanniRodighiero** [vcoppe/gpx-tool#5]
Hello, I was playing around with gpxstudio planning some itineraries in order to go mountain biking on local tracks.
On thing very important to me is the elevation (in the end the total climb) of the itinerary I planned and I was wondering how this parameter is calculated. I mean for each point, how do you get the elevation value? Mapbox  apis?

If I compare the gpx produced with gpxstudio and the one that comes out of [gpsvisualizer](https://www.gpsvisualizer.com/elevation) for instance, the results are very different and I'm trying to understand which one is more reliable.

Thanks in advance and keep up the good job your doing on this website!

**Comment by vcoppe** [comment]
I use Mapbox's [Terrain-RGB tiles](https://docs.mapbox.com/help/troubleshooting/access-elevation-data/#mapbox-terrain-rgb) which provide grid elevation data within a square. I then interpolate the 4 values closest to the given coordinates.
There are 512x512 values in each grid and you can see [here](https://docs.mapbox.com/help/glossary/zoom-level/#zoom-levels-and-geographical-distance) to which distance it corresponds depending on the latitude.
I have just increased the resolution of the elevation data to level 9 tiles and tweaked the computation of the elevation gain a little bit. As you can see [here](https://www.gpsvisualizer.com/tutorials/elevation_gain.html), the computation of the elevation gain is not something trivial and unfortunately there is no best way to do it.

**Comment by giovanniRodighiero** [comment]
Ok, I understand, thanks for the complete answer.

I'm closing the issue since I got the info I was looking for!
