### ISSUE TITLE
Localization (Translation)

### ISSUE THREAD

**Issue by KovalevArtem** [vcoppe/gpx-tool#6]
It is sad that the site is only in En - I propose to translate.
I am ready to help in the translation into Russian.
(For example, you can use Weblate, or any other service. It is completely free for open source projects.)

![image](https://user-images.githubusercontent.com/36500228/116104274-fb956f80-a6b8-11eb-8c3b-47f6a956b204.png)

**Comment by vcoppe** [comment]
Hi, thanks for proposing this! I have seen that it integrates with Github so it could be perfect.
However, I haven't coded this project with translation in mind so strings are both in html and javascript files.
How can I organize the code to make this easy ?

**Comment by KovalevArtem** [comment]
@comradekingu What would you advise to do in this case?

**Comment by comradekingu** [comment]
Anything out of https://docs.weblate.org/en/latest/formats.html will do.
You could do components for each and see how it goes.
Happy to help and test.

**Comment by vcoppe** [comment]
I think the easiest would probably to migrate all the hard-coded text in Javascript files to HTML so there is only one type od source files to translate. I have seen that I can use a CSS tag to select text to translate, does it work with nested HTML tags? (e.g. text with <b>some other text</b> in the middle)

**Comment by comradekingu** [comment]
Sure. Would have to look out for unintended translations, or sanetize it.

**Comment by comradekingu** [comment]
"There are a"
"lot of sentences that"
"depend on others, and"
"a fixed relation between verb, object and subject."

**Comment by vcoppe** [comment]
Yes, I tried to define strings without any HTML code in it but from a translation perspective, I can understand that it is really inconvenient. Should I try to parse the text as whole sentences but with some HTML in it? That would mean translators should re-use the HTML tags in their translation

**Comment by comradekingu** [comment]
What HTML tags? I think "yes" is the answer, because it is impossible to make sense of the ones that are just articles, or the mid part of the sentence only.

**Comment by vcoppe** [comment]
Sorry I had to remove the project from Weblate because I am not satisfied with this solution.
The goal would be to have the website translated in other languages while keeping the same HTML tags.
It seems that Weblate does not handle that (for example, a simple hyperlink).
I have looked at other tools but for now I have the feeling that there is no straightforward way to handle translation for pure HTML and JS.
[This tool](https://lokalise.com/blog/translate-html-content/) looks quite interesting but it generates one HTML file for each language. So a user would be redirected to a new page when switching the language and potentially lose all his progress made in the tool.

**Comment by KovalevArtem** [comment]
@vcoppe If you have decided unambiguously that Weblate does not suit you, then please take a look at Crowdin. In my opinion, this is a more convenient service for translators than Lokalise!

(But Weblate is certainly better off both 😅)

**Comment by vcoppe** [comment]
I have setup a [Crowdin project](https://crowdin.com/project/gpxstudio). Their support for HTML files is really nice, thanks for the suggestion!

**Comment by comradekingu** [comment]
@vcoppe Don't put my translations on there.
Hopefully Weblate HTML support will have improved by the time you figure out Crowdin produces awful and lacklustre results.
The worst platform, bar none.

**Comment by vcoppe** [comment]
@comradekingu Well, this is my first translation project and @KovalevArtem recommended this software above. I have already done the translation in French and the workflow is exactly as I needed.
